spring.application.name=luna2-auth-service
server.port=8080
server.servlet.context-path=/

# OAuth Configuration
oauth.google.state.secret=
oauth.google.state.ttl.seconds=900

# Logging
logging.level.root=INFO
logging.level.it.zensoftware.luna2.authservice=DEBUG
