<?php
$e = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$money = static fn (mixed $value): string => number_format((float) $value, 2, ',', '.') . ' €';
$date = static fn (mixed $value): string => $value ? date('d/m/Y', strtotime((string) $value)) : '—';
$address = static function (array $party) use ($e): string {
    $city = trim(($party['postal_code'] ?? '') . ' ' . ($party['city'] ?? '') . ' ' . (!empty($party['province']) ? '(' . $party['province'] . ')' : ''));
    return $e($party['address'] ?? '') . ($city !== '' ? '<br>' . $e($city) : '') . '<br>' . $e($party['country_code'] ?? 'IT');
};
?>
<!doctype html><html lang="it"><head><meta charset="utf-8"><style>
@page{margin:18mm 13mm 17mm}body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#172033;line-height:1.35}h1{font-size:19px;margin:0 0 3px;color:#0f2447}h2{font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:#31527c;margin:0 0 7px}.muted{color:#65758b}.top,.parties,.summary{width:100%;border-collapse:collapse}.top td{vertical-align:top;padding:0 0 14px}.top .issuer{text-align:right;width:44%}.doc-meta{border-top:2px solid #193c67;padding-top:7px}.parties{margin:14px 0}.parties td{vertical-align:top;width:50%;padding:10px;border:1px solid #ced8e5}.parties td+td{border-left:0}.lines{width:100%;border-collapse:collapse;margin-top:12px}.lines th{background:#193c67;color:#fff;text-transform:uppercase;font-size:7.2px;letter-spacing:.04em;text-align:left}.lines th,.lines td{padding:6px 5px;border-bottom:1px solid #d7e0ea;vertical-align:top}.right{text-align:right!important}.summary{margin-top:13px}.summary td{vertical-align:top}.totals{width:100%;border-collapse:collapse}.totals td{padding:4px 6px;border-bottom:1px solid #d7e0ea}.totals .grand td{font-size:12px;font-weight:bold;color:#0f2447;border-top:2px solid #193c67}.payment{margin-top:15px;padding:9px;border:1px solid #ced8e5;background:#f6f8fb}.notes{margin-top:13px;padding-top:8px;border-top:1px solid #d7e0ea}.footer{position:fixed;bottom:-8mm;left:0;right:0;border-top:1px solid #ced8e5;padding-top:5px;font-size:7px;color:#65758b;text-align:center}.nowrap{white-space:nowrap}
</style></head><body>
<table class="top"><tr><td><h1><?= $e($definition['singular']) ?> <?= $e($document['number']) ?></h1><div class="doc-meta"><strong>Data:</strong> <?= $date($document['document_date']) ?><br><strong>Valuta:</strong> <?= $e($document['currency'] ?: 'EUR') ?><?php if (!empty($document['fatturapa_type'])): ?><br><strong>Tipo FatturaPA:</strong> <?= $e($document['fatturapa_type']) ?><?php endif; ?></div></td><td class="issuer"><strong><?= $e($organization['business_name'] ?? '') ?></strong><br><?= $address($organization) ?><br>P.IVA <?= $e($organization['vat_number'] ?? '—') ?> · C.F. <?= $e($organization['tax_code'] ?? '—') ?><br>Regime fiscale <?= $e($organization['fiscal_regime'] ?? '—') ?><br><?php if (!empty($organization['sdi_code'])): ?>SDI <?= $e($organization['sdi_code']) ?> · <?php endif; ?><?= $e($organization['pec'] ?? $organization['email'] ?? '') ?><br><?php if (!empty($organization['phone'])): ?>Tel. <?= $e($organization['phone']) ?><?php endif; ?></td></tr></table>
<table class="parties"><tr><td><h2><?= $document['counterparty_type'] === 'SUPPLIER' ? 'Fornitore' : 'Cliente / destinatario' ?></h2><strong><?= $e($counterparty['business_name'] ?? $document['counterparty_name']) ?></strong><br><?= $address($counterparty) ?></td><td><h2>Dati fiscali controparte</h2>P.IVA: <strong><?= $e($counterparty['vat_number'] ?? '—') ?></strong><br>C.F.: <?= $e($counterparty['tax_code'] ?? '—') ?><br>Codice SDI: <?= $e($counterparty['sdi_code'] ?? '—') ?><br>PEC: <?= $e($counterparty['pec'] ?? '—') ?><?php if (!empty($document['subject'])): ?><br><br><strong>Oggetto:</strong> <?= $e($document['subject']) ?><?php endif; ?></td></tr></table>
<table class="lines"><thead><tr><th>#</th><th>Codice / descrizione</th><th class="right">Q.tà</th><th>U.M.</th><th class="right">Prezzo</th><th class="right">Sc. %</th><th class="right">Imponibile</th><th class="right">IVA</th><th class="right">Totale</th></tr></thead><tbody><?php foreach ($lines as $line): ?><tr><td><?= (int) $line['line_number'] ?></td><td><?php if (!empty($line['product_code'])): ?><strong><?= $e($line['product_code']) ?></strong><br><?php endif; ?><?= $e($line['description']) ?><?php if (!empty($line['vat_nature'])): ?><br><span class="muted">Natura <?= $e($line['vat_nature']) ?></span><?php endif; ?></td><td class="right"><?= number_format((float) $line['quantity'], 2, ',', '.') ?></td><td><?= $e($line['unit'] ?: 'NR') ?></td><td class="right nowrap"><?= $money($line['unit_price']) ?></td><td class="right"><?= number_format((float) $line['discount_percent'], 2, ',', '.') ?></td><td class="right nowrap"><?= $money($line['taxable_amount']) ?></td><td class="right"><?= number_format((float) $line['vat_rate'], 2, ',', '.') ?>%</td><td class="right nowrap"><?= $money($line['total_amount']) ?></td></tr><?php endforeach; ?></tbody></table>
<table class="summary"><tr><td style="width:50%;padding-right:18px"><h2>Pagamento</h2><strong><?= $e($document['payment_terms_label'] ?? 'Condizioni non specificate') ?></strong><br>Modalità: <?= $e($document['payment_method_code'] ?? '—') ?><br>Scadenza: <?= $date($document['due_date']) ?><?php if (!empty($document['bank_name']) || !empty($document['bank_iban'])): ?><br>Banca: <?= $e($document['bank_name'] ?? '') ?><?php if (!empty($document['bank_abi'])): ?> · ABI <?= $e($document['bank_abi']) ?><?php endif; ?><?php if (!empty($document['bank_cab'])): ?> · CAB <?= $e($document['bank_cab']) ?><?php endif; ?><?php if (!empty($document['bank_iban'])): ?><br>IBAN <?= $e($document['bank_iban']) ?><?php endif; ?><?php endif; ?></td><td style="width:50%"><table class="totals"><tr><td>Imponibile</td><td class="right"><?= $money($document['taxable_total']) ?></td></tr><tr><td>IVA</td><td class="right"><?= $money($document['vat_total']) ?></td></tr><?php if ((float) $document['stamp_duty_total'] > 0): ?><tr><td>Bollo</td><td class="right"><?= $money($document['stamp_duty_total']) ?></td></tr><?php endif; ?><?php if ((float) $document['withholding_total'] > 0): ?><tr><td>Ritenuta <?= number_format((float) $document['withholding_rate'], 2, ',', '.') ?>%</td><td class="right">− <?= $money($document['withholding_total']) ?></td></tr><?php endif; ?><tr class="grand"><td>Totale documento</td><td class="right"><?= $money($document['total']) ?></td></tr><tr><td><strong>Netto da pagare</strong></td><td class="right"><strong><?= $money($document['balance_due']) ?></strong></td></tr></table></td></tr></table>
<?php if ((float) $document['withholding_total'] > 0): ?><div class="payment"><strong>Ritenuta d’acconto:</strong> tipo <?= $e($document['withholding_type']) ?>, imponibile <?= number_format((float) $document['withholding_taxable_percent'], 2, ',', '.') ?>%, aliquota <?= number_format((float) $document['withholding_rate'], 2, ',', '.') ?>%, causale <?= $e($document['withholding_cause'] ?? '—') ?>.</div><?php endif; ?>
<?php if (!empty($document['notes'])): ?><div class="notes"><h2>Note</h2><?= nl2br($e($document['notes'])) ?></div><?php endif; ?>
<div class="footer"><?= $e($organization['business_name'] ?? '') ?> · P.IVA <?= $e($organization['vat_number'] ?? '') ?> · Documento generato da Luna2 il <?= date('d/m/Y H:i') ?></div>
</body></html>
