CREATE TABLE IF NOT EXISTS admin_operations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    area VARCHAR(40) NOT NULL,
    title VARCHAR(180) NOT NULL,
    operation_type VARCHAR(60) NOT NULL,
    status VARCHAR(20) NOT NULL,
    due_date DATE NULL,
    counterparty VARCHAR(150) NULL,
    reference_code VARCHAR(80) NULL,
    amount_due DECIMAL(15,2) NULL,
    owner_user_id BIGINT NULL,
    notes TEXT NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_admin_ops_area (area),
    INDEX idx_admin_ops_status (status),
    INDEX idx_admin_ops_due (due_date),
    CONSTRAINT fk_admin_ops_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
);
