<?php

declare(strict_types=1);

namespace Luna\Controller;

use Luna\Core\Auth;
use Luna\Service\CalendarService;
use Luna\Service\EcommerceService;
use Luna\Service\RentalService;

final class OperationsIntegrationController extends BaseController
{
    public function ecommerce(): never{$this->requireFeature('ecommerce');$this->requireRoles(['OWNER','ADMIN','SALES']);$org=Auth::organizationId();$channels=$this->rows('SELECT * FROM ecommerce_channels WHERE organization_id=? ORDER BY name',[$org]);$orders=$this->rows('SELECT o.*,c.name channel_name FROM ecommerce_orders o LEFT JOIN ecommerce_channels c ON c.id=o.ecommerce_channel_id WHERE o.organization_id=? ORDER BY o.order_date DESC,o.id DESC LIMIT 300',[$org]);$catalog=$this->rows('SELECT ep.*,c.name channel_name,p.code local_code FROM ecommerce_products ep LEFT JOIN ecommerce_channels c ON c.id=ep.ecommerce_channel_id LEFT JOIN products p ON p.id=ep.product_id WHERE ep.organization_id=? ORDER BY ep.updated_at DESC LIMIT 300',[$org]);$queue=$this->rows('SELECT q.*,c.name channel_name FROM ecommerce_sync_queue q INNER JOIN ecommerce_channels c ON c.id=q.ecommerce_channel_id WHERE q.organization_id=? ORDER BY q.id DESC LIMIT 100',[$org]);$this->view->render('operations/ecommerce',compact('channels','orders','catalog','queue')+['title'=>'Hub e-commerce']);}
    public function enqueue(string $id): never{$this->requireRoles(['OWNER','ADMIN','SALES']);$operation=(string)($_POST['operation']??'PULL_ORDERS');$entityType=$operation==='ACK_ORDER'?'ecommerce_orders':(in_array($operation,['PUSH_STOCK','PUSH_PRICES'],true)?'products':null);$entityId=(int)($operation==='ACK_ORDER'?($_POST['ecommerce_order_id']??0):($_POST['product_id']??0))?:null;(new EcommerceService($this->db,Auth::organizationId(),Auth::id()))->enqueue((int)$id,$operation,$entityType,$entityId,['product_id'=>(int)($_POST['product_id']??0),'ecommerce_order_id'=>(int)($_POST['ecommerce_order_id']??0)]);$this->redirect('/operations/ecommerce','Operazione accodata.');}
    public function processCommerce(): never{$this->requireRoles(['OWNER','ADMIN']);$r=(new EcommerceService($this->db,Auth::organizationId(),Auth::id()))->processQueue();$this->redirect('/operations/ecommerce','Coda elaborata: '.$r['processed'].' completate, '.$r['failed'].' non riuscite.',$r['failed']?'error':'success');}
    public function convertOrder(string $id): never{$this->requireRoles(['OWNER','ADMIN','SALES']);$doc=(new EcommerceService($this->db,Auth::organizationId(),Auth::id()))->convertOrder((int)$id);$this->redirect('/documents/orders/'.$doc,'Ordine cliente creato dal canale e-commerce.');}
    public function webhook(string $id): never
    {
        $statement=$this->db->prepare('SELECT organization_id,platform FROM ecommerce_channels WHERE id=? AND active=1');$statement->execute([(int)$id]);$channel=$statement->fetch();if(!$channel){http_response_code(404);exit;}
        $raw=(string)file_get_contents('php://input');$headers=function_exists('getallheaders')?(getallheaders()?:[]):[];$payload=json_decode($raw,true)?:[];$header=static function(string $name)use($headers):string{foreach($headers as $key=>$value){if(strcasecmp((string)$key,$name)===0){return is_array($value)?(string)reset($value):(string)$value;}}return '';};
        $event=$header('X-WC-Webhook-Topic')?:($header('X-Shopify-Topic')?:($header('X-Luna-Event')?:'order.updated'));$external=$header('X-WC-Webhook-Delivery-ID')?:($header('X-Shopify-Webhook-Id')?:(string)($payload['id']??$payload['orderId']??''));
        (new EcommerceService($this->db,(int)$channel['organization_id']))->acceptWebhook((int)$id,$event,$external,$raw,$headers);header('Content-Type: application/json');http_response_code(202);echo '{"accepted":true}';exit;
    }
    public function rental(): never{$this->requireFeature('rental');$this->requireRoles(['OWNER','ADMIN','SALES','VIEWER']);$org=Auth::organizationId();$contracts=$this->rows('SELECT * FROM rental_contracts WHERE organization_id=? ORDER BY end_date,status',[$org]);$tickets=$this->rows('SELECT t.*,c.contract_number,u.name assignee_name FROM rental_tickets t LEFT JOIN rental_contracts c ON c.id=t.rental_contract_id LEFT JOIN users u ON u.id=t.assigned_to WHERE t.organization_id=? ORDER BY FIELD(t.status,\'OPEN\',\'IN_PROGRESS\',\'WAITING\',\'RESOLVED\',\'CLOSED\'),t.priority DESC,t.opened_at DESC',[$org]);$deadlines=$this->rows('SELECT d.*,c.contract_number FROM rental_deadlines d LEFT JOIN rental_contracts c ON c.id=d.rental_contract_id WHERE d.organization_id=? AND d.status IN (\'OPEN\',\'OVERDUE\') ORDER BY d.due_date',[$org]);$users=$this->rows('SELECT id,name FROM users WHERE organization_id=? AND active=1 ORDER BY name',[$org]);$this->view->render('operations/rental',compact('contracts','tickets','deadlines','users')+['title'=>'Noleggio e assistenza']);}
    public function meter(string $id): never{$this->requireRoles(['OWNER','ADMIN','SALES']);(new RentalService($this->db,Auth::organizationId(),Auth::id()))->recordMeter((int)$id,(string)$_POST['reading_date'],(int)$_POST['kilometers'],'MANUAL',$_POST['notes']??null);$this->redirect('/operations/rental','Chilometraggio aggiornato.');}
    public function ticket(string $id): never{$this->requireRoles(['OWNER','ADMIN','SALES']);(new RentalService($this->db,Auth::organizationId(),Auth::id()))->changeTicketStatus((int)$id,(string)$_POST['status'],$_POST['notes']??null,(int)($_POST['assigned_to']??0)?:null);$this->redirect('/operations/rental','Ticket aggiornato.');}
    public function automateRental(): never{$this->requireRoles(['OWNER','ADMIN']);$r=(new RentalService($this->db,Auth::organizationId(),Auth::id()))->runAutomations();$this->redirect('/operations/rental','Automazioni: '.$r['deadlines'].' scadenze, '.$r['breaches'].' SLA, '.$r['invoices'].' fatture.');}
    public function calendar(): never{$this->requireFeature('calendar');$org=Auth::organizationId();$accounts=$this->rows('SELECT ca.*,u.name user_name FROM calendar_accounts ca INNER JOIN users u ON u.id=ca.user_id WHERE ca.organization_id=? ORDER BY u.name,ca.provider',[$org]);$events=$this->rows('SELECT e.*,ca.account_email FROM calendar_events e LEFT JOIN calendar_accounts ca ON ca.id=e.calendar_account_id WHERE e.organization_id=? AND e.deleted_external=0 AND e.starts_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) ORDER BY e.starts_at LIMIT 500',[$org]);$logs=$this->rows('SELECT l.*,ca.account_email FROM calendar_sync_logs l INNER JOIN calendar_accounts ca ON ca.id=l.calendar_account_id WHERE l.organization_id=? ORDER BY l.id DESC LIMIT 50',[$org]);$users=$this->rows('SELECT id,name FROM users WHERE organization_id=? AND active=1 ORDER BY name',[$org]);$this->view->render('operations/calendar',compact('accounts','events','logs','users')+['title'=>'Calendari sincronizzati']);}
    public function calendarSettings(): never
    {
        $this->requireRoles(['OWNER','ADMIN']);$org=Auth::organizationId();$user=(int)($_POST['user_id']??0);$check=$this->db->prepare('SELECT 1 FROM users WHERE id=? AND organization_id=? AND active=1');$check->execute([$user,$org]);if(!$check->fetchColumn()){throw new \InvalidArgumentException('Utente non valido.');}
        $provider=(string)($_POST['provider']??'GOOGLE');$auth=(string)($_POST['auth_type']??'OAUTH2');$endpoint=trim((string)($_POST['endpoint_url']??''))?:null;if(!in_array($provider,['GOOGLE','ICLOUD','CALDAV'],true)||!in_array($auth,['OAUTH2','BASIC','APP_PASSWORD','BEARER'],true)){throw new \InvalidArgumentException('Configurazione calendario non valida.');}if($provider!=='GOOGLE'&&(!$endpoint||!str_starts_with($endpoint,'https://'))){throw new \InvalidArgumentException('Per CalDAV/iCloud è necessario un endpoint HTTPS.');}
        $email=mb_strtolower(trim((string)($_POST['account_email']??'')));$existing=$this->db->prepare('SELECT id FROM calendar_accounts WHERE organization_id=? AND user_id=? AND provider=? AND account_email=? LIMIT 1');$existing->execute([$org,$user,$provider,$email]);$id=$existing->fetchColumn();
        if($id){$this->db->prepare('UPDATE calendar_accounts SET endpoint_url=?,auth_type=?,secret_reference=?,external_calendar_id=?,active=1,updated_by=?,updated_at=NOW() WHERE id=?')->execute([$endpoint,$auth,trim((string)$_POST['secret_reference']),trim((string)($_POST['external_calendar_id']??''))?:null,Auth::id(),$id]);}else{$this->db->prepare('INSERT INTO calendar_accounts (organization_id,user_id,provider,account_email,endpoint_url,auth_type,secret_reference,external_calendar_id,active,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,1,?,?,NOW(),NOW())')->execute([$org,$user,$provider,$email,$endpoint,$auth,trim((string)$_POST['secret_reference']),trim((string)($_POST['external_calendar_id']??''))?:null,Auth::id(),Auth::id()]);}
        $this->redirect('/operations/calendar','Account calendario configurato.');
    }
    public function syncCalendar(string $id): never{$r=(new CalendarService($this->db,Auth::organizationId(),Auth::id()))->sync((int)$id);$this->redirect('/operations/calendar','Sincronizzazione completata: '.$r['processed'].' eventi, '.$r['errors'].' errori.',$r['errors']?'error':'success');}
    private function rows(string $sql,array $p):array{$s=$this->db->prepare($sql);$s->execute($p);return $s->fetchAll();}
}
