<?php

declare(strict_types=1);

return [
    'anagraphics' => [
        'label' => 'Anagrafiche',
        'description' => 'Clienti, fornitori e contatti aziendali.',
        'icon' => 'users',
        'required_tables' => ['customers', 'suppliers'],
        'default' => true,
    ],
    'sales' => [
        'label' => 'Vendite',
        'description' => 'Preventivi, ordini, DDT, proforma e fatturazione attiva.',
        'icon' => 'receipt',
        'required_tables' => ['documents', 'document_lines', 'document_sequences'],
        'default' => true,
    ],
    'purchases' => [
        'label' => 'Acquisti',
        'description' => 'Ordini fornitori e fatture passive.',
        'icon' => 'bag',
        'required_tables' => ['suppliers', 'documents', 'document_lines'],
        'default' => true,
    ],
    'inventory' => [
        'label' => 'Prodotti e magazzino',
        'description' => 'Catalogo, giacenze, magazzini e movimenti.',
        'icon' => 'box',
        'required_tables' => ['products', 'warehouses', 'inventory_movements', 'inventory_balances', 'inventory_transfers', 'inventory_pick_lists', 'inventory_barcode_events'],
        'default' => true,
    ],
    'crm' => [
        'label' => 'CRM',
        'description' => 'Lead, opportunità e attività commerciali.',
        'icon' => 'target',
        'required_tables' => ['leads', 'activities', 'pipeline_stages'],
        'default' => true,
    ],
    'projects' => [
        'label' => 'Commesse',
        'description' => 'Progetti, avanzamento, budget e consuntivi.',
        'icon' => 'briefcase',
        'required_tables' => ['projects', 'project_lines', 'project_time_entries', 'project_expenses', 'project_milestones'],
        'default' => true,
    ],
    'accounting' => [
        'label' => 'Contabilità',
        'description' => 'Prima nota, mastri, registri e liquidazioni IVA, bilanci, scadenze e cespiti.',
        'icon' => 'calculator',
        'required_tables' => [
            'chart_of_accounts', 'journal_entries', 'journal_entry_lines', 'accounting_settings', 'accounting_causes',
            'accounting_account_mappings', 'vat_registers', 'vat_movements', 'vat_settlements', 'vat_settlement_details',
            'accounting_open_items', 'payment_allocations', 'vat_cash_events', 'bank_accounts', 'bank_transactions',
            'reconciliation_links', 'vat_adjustments', 'lipe_communications', 'vat_annual_summaries',
            'accounting_period_locks', 'accounting_closing_runs', 'accounting_adjustment_schedules',
            'tax_deadlines', 'fixed_assets', 'fixed_asset_categories', 'depreciation_entries',
            'withholding_records', 'api_endpoint_configs',
        ],
        'default' => true,
    ],
    'professional' => [
        'label' => 'Centro professionale',
        'description' => 'Qualità dati, stampe numerate, fascicoli adempimenti e import bancari.',
        'icon' => 'lock',
        'required_tables' => [
            'workspace_notifications', 'saved_views', 'onboarding_progress', 'bulk_operations',
            'official_print_runs', 'compliance_filing_runs', 'bank_statement_imports',
            'bank_reconciliation_suggestions',
        ],
        'default' => true,
    ],
    'calendar' => [
        'label' => 'Calendario',
        'description' => 'Agenda operativa ed eventi sincronizzati.',
        'icon' => 'calendar',
        'required_tables' => ['calendar_events', 'calendar_accounts', 'calendar_sync_logs'],
        'default' => true,
    ],
    'communications' => [
        'label' => 'Comunicazioni',
        'description' => 'Invio e-mail, code, allegati e tracciamento delle comunicazioni.',
        'icon' => 'receipt',
        'required_tables' => ['communication_settings', 'outbound_emails', 'email_events'],
        'default' => true,
    ],
    'management_reports' => [
        'label' => 'Report direzionali',
        'description' => 'Analisi economiche, operative ed esportazioni direzionali.',
        'icon' => 'download',
        'required_tables' => ['report_exports'],
        'default' => true,
    ],
    'hr' => [
        'label' => 'Personale',
        'description' => 'Presenze, approvazioni ed elaborazioni paghe.',
        'icon' => 'id-card',
        'required_tables' => ['time_records', 'leave_requests', 'leave_balances', 'approval_requests', 'payroll_runs', 'payroll_details', 'payroll_employee_configs'],
        'default' => true,
    ],
    'leave_payroll' => [
        'label' => 'Ferie e paghe',
        'description' => 'Ferie, permessi, approvazioni e gestione dei cedolini importati.',
        'icon' => 'id-card',
        'required_tables' => ['leave_requests', 'leave_balances', 'approval_requests', 'payroll_runs', 'payroll_details', 'payroll_employee_configs'],
        'default' => true,
    ],
    'ecommerce' => [
        'label' => 'E-commerce',
        'description' => 'Canali, ordini e sincronizzazioni marketplace.',
        'icon' => 'store',
        'required_tables' => ['ecommerce_channels', 'ecommerce_orders', 'ecommerce_order_lines', 'ecommerce_sync_queue'],
        'default' => false,
    ],
    'rental' => [
        'label' => 'Noleggio',
        'description' => 'Contratti, scadenze e ticket di assistenza.',
        'icon' => 'car',
        'required_tables' => ['rental_contracts', 'rental_tickets', 'rental_deadlines', 'rental_meter_readings', 'rental_ticket_events'],
        'default' => false,
    ],
    'imports' => [
        'label' => 'Importazioni',
        'description' => 'Migrazione DATEV Koinos e importazioni massive.',
        'icon' => 'upload',
        'required_tables' => ['import_batches', 'import_files', 'import_rows', 'import_records'],
        'default' => true,
    ],
];
