<?php use Luna\Core\Csrf; use Luna\Core\View; $editable = in_array($entry['status'], ['DRAFT','POSTED'], true) && $entry['source_type'] === 'MANUAL' && empty($entry['is_finalized']); $quickAccountChange = in_array($entry['status'], ['DRAFT','POSTED'], true) && empty($entry['is_finalized']); ?>
<section class="page-intro compact"><div><a class="back-link" href="/accounting/journal">← Prima nota</a><span class="eyebrow">Registrazione <?= View::e($entry['protocol_number']) ?></span><h1><?= View::e($entry['description']) ?></h1><p><?= View::date($entry['entry_date']) ?> · <?= View::e($entry['entry_type']) ?><?= $entry['counterparty'] ? ' · ' . View::e($entry['counterparty']) : '' ?></p></div><div class="inline-actions"><?php if ($editable): ?><a class="button ghost" href="/accounting/journal/<?= (int) $entry['id'] ?>/edit">Modifica</a><?php endif; ?><?php if ($entry['status'] === 'DRAFT' && $entry['source_type'] === 'MANUAL'): ?><form method="post" action="/accounting/journal/<?= (int) $entry['id'] ?>/post"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="button primary" type="submit"><?= View::icon('check') ?> Contabilizza</button></form><?php endif; ?></div></section>

<section class="accounting-kpis entry-kpis"><article><span>Stato</span><strong><span class="badge status-<?= !empty($entry['is_finalized']) ? 'locked' : strtolower((string) $entry['status']) ?>"><?= $entry['status'] === 'POSTED' ? (!empty($entry['is_finalized']) ? 'Definitiva' : 'Provvisoria') : View::e(View::label($entry['status'])) ?></span></strong></article><article><span>Totale Dare</span><strong><?= View::money($entry['total_debit']) ?></strong></article><article><span>Totale Avere</span><strong><?= View::money($entry['total_credit']) ?></strong></article><article><span>Documento</span><strong><?= View::e($entry['document_number'] ?: '—') ?></strong></article></section>

<?php if ($entry['status'] === 'POSTED' && empty($entry['is_finalized'])): ?><div class="notice info">Scrittura contabilizzata provvisoriamente: è inclusa in bilanci, mastrini e libro giornale, ma resta modificabile finché il periodo non viene reso definitivo.</div><?php elseif (!empty($entry['is_finalized'])): ?><div class="notice success">Scrittura definitiva dal <?= View::date($entry['finalized_at']) ?>. Per correggerla occorre una registrazione di storno.</div><?php endif; ?>

<?php $entryYear = (int) substr((string) $entry['entry_date'], 0, 4); ?>
<section class="card data-card"><div class="card-header"><div><span class="section-kicker">Dettaglio contabile</span><h2>Movimenti</h2><?php if ($quickAccountChange): ?><p class="help">Puoi sostituire il conto di una riga senza modificare importi, IVA o collegamento al documento.</p><?php endif; ?></div><span class="score"><?= count($lines) ?></span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Conto</th><th>Descrizione</th><th>Dare</th><th>Avere</th><?php if ($quickAccountChange): ?><th>Azioni</th><?php endif; ?></tr></thead><tbody><?php foreach ($lines as $line): ?><tr><td><?= (int) $line['line_number'] ?></td><td class="primary-cell"><a class="statement-account-link" href="/accounting/ledger/<?= (int) $line['account_id'] ?>?from=<?= $entryYear ?>-01-01&amp;to=<?= $entryYear ?>-12-31"><?= View::e($line['account_code']) ?></a><small><?= View::e($line['account_name']) ?></small></td><td><?= View::e($line['description'] ?: $entry['description']) ?></td><td><?= View::money($line['debit']) ?></td><td><?= View::money($line['credit']) ?></td><?php if ($quickAccountChange): ?><td><details class="quick-account-change"><summary class="table-action">Cambia conto</summary><form method="post" action="/accounting/journal/<?= (int) $entry['id'] ?>/lines/<?= (int) $line['id'] ?>/account"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><label><span>Nuovo conto</span><select name="account_id" required><option value="">Seleziona…</option><?php foreach ($accounts as $account): if ($account['account_type'] !== $line['account_type'] || (int) $account['id'] === (int) $line['account_id']) continue; ?><option value="<?= (int) $account['id'] ?>"><?= View::e($account['code'] . ' · ' . $account['name']) ?></option><?php endforeach; ?></select></label><label><span>Motivo della modifica</span><input name="reason" maxlength="350" placeholder="Es. corretta classificazione del costo" required></label><button class="button primary" type="submit">Conferma cambio</button></form></details></td><?php endif; ?></tr><?php endforeach; ?></tbody><tfoot><tr><th colspan="3">Totali</th><th><?= View::money($entry['total_debit']) ?></th><th><?= View::money($entry['total_credit']) ?></th><?php if ($quickAccountChange): ?><th></th><?php endif; ?></tr></tfoot></table></div></section>
<?php if ($entry['notes']): ?><section class="card accounting-note"><span class="section-kicker">Note</span><p><?= nl2br(View::e($entry['notes'])) ?></p></section><?php endif; ?>
<?php if (!empty($revisions)): ?><section class="card data-card"><div class="card-header"><div><span class="section-kicker">Tracciabilità</span><h2>Storico revisioni</h2></div><span class="score"><?= count($revisions) ?></span></div><div class="table-wrap"><table><thead><tr><th>Versione precedente</th><th>Data modifica</th><th>Utente</th><th>Motivo</th></tr></thead><tbody><?php foreach ($revisions as $revision): ?><tr><td>n. <?= (int) $revision['revision_number'] ?></td><td><?= View::date($revision['changed_at']) ?></td><td><?= View::e($revision['changed_by_name'] ?: 'Sistema') ?></td><td><?= View::e($revision['change_reason']) ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($entry['status'] === 'DRAFT' && $entry['source_type'] === 'MANUAL'): ?><form method="post" action="/accounting/journal/<?= (int) $entry['id'] ?>/delete" data-confirm="Eliminare definitivamente questa bozza?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="button ghost danger-text" type="submit">Elimina bozza</button></form><?php endif; ?>
