<?php use Luna\Core\Csrf; use Luna\Core\View; $editable = in_array($entry['status'], ['DRAFT','POSTED'], true) && $entry['source_type'] === 'MANUAL' && empty($entry['is_finalized']); $quickAccountChange = in_array($entry['status'], ['DRAFT','POSTED'], true) && empty($entry['is_finalized']); ?>
<section class="page-intro compact"><div><a class="back-link" href="/accounting/journal">← Prima nota</a><span class="eyebrow">Registrazione <?= View::e($entry['protocol_number']) ?></span><h1><?= View::e($entry['description']) ?></h1><p><?= View::date($entry['entry_date']) ?> · <?= View::e($entry['entry_type']) ?><?= $entry['counterparty'] ? ' · ' . View::e($entry['counterparty']) : '' ?></p></div><div class="inline-actions"><?php if ($editable): ?><a class="button ghost" href="/accounting/journal/<?= (int) $entry['id'] ?>/edit">Modifica</a><?php endif; ?><?php if ($entry['status'] === 'DRAFT' && $entry['source_type'] === 'MANUAL'): ?><form method="post" action="/accounting/journal/<?= (int) $entry['id'] ?>/post"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="button primary" type="submit"><?= View::icon('check') ?> Contabilizza</button></form><?php endif; ?></div></section>

<section class="accounting-kpis entry-kpis"><article><span>Stato</span><strong><span class="badge status-<?= !empty($entry['is_finalized']) ? 'locked' : strtolower((string) $entry['status']) ?>"><?= $entry['status'] === 'POSTED' ? (!empty($entry['is_finalized']) ? 'Definitiva' : 'Provvisoria') : View::e(View::label($entry['status'])) ?></span></strong></article><article><span>Totale Dare</span><strong><?= View::money($entry['total_debit']) ?></strong></article><article><span>Totale Avere</span><strong><?= View::money($entry['total_credit']) ?></strong></article><article><span>Documento</span><strong><?= View::e($entry['document_number'] ?: '—') ?></strong></article></section>

<?php if ($entry['status'] === 'POSTED' && empty($entry['is_finalized'])): ?><div class="notice info">Scrittura contabilizzata provvisoriamente: è inclusa in bilanci, mastrini e libro giornale, ma resta modificabile finché il periodo non viene reso definitivo.</div><?php elseif (!empty($entry['is_finalized'])): ?><div class="notice success">Scrittura definitiva dal <?= View::date($entry['finalized_at']) ?>. Per correggerla occorre una registrazione di storno.</div><?php endif; ?>

<?php if ($sourceDocument && in_array($entry['status'], ['DRAFT','POSTED'], true) && empty($entry['is_finalized'])): ?>
<section class="card registration-date-card"><div><span class="eyebrow">Documento collegato <?= View::e($sourceDocument['number']) ?></span><h2>Correggi data di registrazione</h2><p>La data documento <?= View::date($sourceDocument['document_date']) ?> resta invariata. Luna aggiorna insieme questa prima nota, la fattura e il periodo IVA.</p></div><form method="post" action="/accounting/journal/<?= (int) $entry['id'] ?>/registration-date" class="inline-form" data-confirm="Confermare la nuova data e riallineare documento e IVA?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><label><span>Data registrazione</span><input type="date" name="registration_date" min="<?= View::e($sourceDocument['document_date']) ?>" value="<?= View::e($sourceDocument['registration_date'] ?: $entry['entry_date']) ?>" required></label><button class="button primary" type="submit">Aggiorna data</button></form></section>
<?php endif; ?>

<?php $entryYear = (int) substr((string) $entry['entry_date'], 0, 4); ?>
<section class="card data-card"><div class="card-header"><div><span class="section-kicker">Dettaglio contabile</span><h2>Movimenti</h2><?php if ($quickAccountChange): ?><p class="help">Puoi sostituire il conto di una riga senza modificare importi, IVA o collegamento al documento.</p><?php endif; ?></div><span class="score"><?= count($lines) ?></span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Conto</th><th>Descrizione</th><th>Dare</th><th>Avere</th><?php if ($quickAccountChange): ?><th class="actions-column">Azioni</th><?php endif; ?></tr></thead><tbody><?php foreach ($lines as $line): ?><tr><td><?= (int) $line['line_number'] ?></td><td class="primary-cell"><a class="statement-account-link" href="/accounting/ledger/<?= (int) $line['account_id'] ?>?from=<?= $entryYear ?>-01-01&amp;to=<?= $entryYear ?>-12-31"><?= View::e($line['account_code']) ?></a><small><?= View::e($line['account_name']) ?></small></td><td><?= View::e($line['description'] ?: $entry['description']) ?></td><td><?= View::money($line['debit']) ?></td><td><?= View::money($line['credit']) ?></td><?php if ($quickAccountChange): ?><td class="actions-column"><button class="table-action" type="button" data-open-account-change data-action="/accounting/journal/<?= (int) $entry['id'] ?>/lines/<?= (int) $line['id'] ?>/account" data-account-type="<?= View::e($line['account_type']) ?>" data-current-account="<?= (int) $line['account_id'] ?>" data-line-label="<?= View::e('Riga ' . $line['line_number'] . ' · ' . $line['account_code'] . ' · ' . $line['account_name']) ?>">Cambia conto</button></td><?php endif; ?></tr><?php endforeach; ?></tbody><tfoot><tr><th colspan="3">Totali</th><th><?= View::money($entry['total_debit']) ?></th><th><?= View::money($entry['total_credit']) ?></th><?php if ($quickAccountChange): ?><th></th><?php endif; ?></tr></tfoot></table></div></section>
<?php if ($quickAccountChange): ?>
<dialog class="account-change-dialog" data-account-change-dialog aria-labelledby="account-change-title">
    <form method="post" data-account-change-form>
        <input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>">
        <header><div><span class="section-kicker">Riclassificazione rapida</span><h2 id="account-change-title">Cambia conto</h2><p data-account-change-line></p></div><button type="button" class="dialog-close" data-close-account-change aria-label="Chiudi">×</button></header>
        <div class="account-change-body">
            <label class="field"><span>Cerca il nuovo conto *</span><div class="account-lookup" data-account-lookup><input type="search" data-account-search placeholder="Digita codice o descrizione…" autocomplete="off" required aria-autocomplete="list" aria-expanded="false"><input type="hidden" name="account_id" data-account-value><div class="account-lookup-results" data-account-results role="listbox" hidden></div></div><small>Sono mostrati soltanto conti compatibili con la riga selezionata.</small></label>
            <label class="field"><span>Motivo della modifica <small>(facoltativo)</small></span><input name="reason" maxlength="350" placeholder="Es. corretta classificazione del costo"></label>
        </div>
        <footer><button class="button ghost" type="button" data-close-account-change>Annulla</button><button class="button primary" type="submit">Conferma cambio</button></footer>
    </form>
</dialog>
<script type="application/json" data-account-catalog><?= json_encode(array_map(static fn (array $account): array => ['id' => (int) $account['id'], 'code' => (string) $account['code'], 'name' => (string) $account['name'], 'type' => (string) $account['account_type']], $accounts), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP) ?></script>
<?php endif; ?>
<?php if ($entry['notes']): ?><section class="card accounting-note"><span class="section-kicker">Note</span><p><?= nl2br(View::e($entry['notes'])) ?></p></section><?php endif; ?>
<?php if (!empty($revisions)): ?><section class="card data-card"><div class="card-header"><div><span class="section-kicker">Tracciabilità</span><h2>Storico revisioni</h2></div><span class="score"><?= count($revisions) ?></span></div><div class="table-wrap"><table><thead><tr><th>Versione precedente</th><th>Data modifica</th><th>Utente</th><th>Motivo</th></tr></thead><tbody><?php foreach ($revisions as $revision): ?><tr><td>n. <?= (int) $revision['revision_number'] ?></td><td><?= View::date($revision['changed_at']) ?></td><td><?= View::e($revision['changed_by_name'] ?: 'Sistema') ?></td><td><?= View::e($revision['change_reason']) ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($entry['status'] === 'DRAFT' && $entry['source_type'] === 'MANUAL'): ?><form method="post" action="/accounting/journal/<?= (int) $entry['id'] ?>/delete" data-confirm="Eliminare definitivamente questa bozza?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="button ghost danger-text" type="submit">Elimina bozza</button></form><?php endif; ?>
