<?php use Luna\Core\Csrf; use Luna\Core\View; $selectedAccount = $selectedAccount ?? []; $selectedRegister = $selectedRegister ?? []; $selectedCause = $selectedCause ?? []; ?>
<section class="page-intro compact"><div><span class="eyebrow">Contabilità · struttura</span><h1>Configurazione contabile</h1><p>Piano dei conti gerarchico, automatismi, causali e sezionali IVA in un unico punto.</p></div><div class="inline-actions"><a class="button ghost" href="/accounting/journal">Prima nota</a><a class="button ghost" href="/accounting/treasury">Tesoreria</a></div></section>
<nav class="accounting-tabs"><a href="#settings">Regole</a><a href="#chart">Piano dei conti</a><a href="#mappings">Automatismi</a><a href="#registers">Sezionali</a><a href="#causes">Causali</a></nav>

<section class="card" id="settings"><div class="card-header"><div><span class="section-kicker">Regole aziendali</span><h2>Impostazioni contabili e IVA</h2></div></div>
<form method="post" action="/accounting/setup/settings" class="modern-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><div class="form-grid">
<label class="field"><span>Principio contabile</span><select name="accounting_basis"><option value="ACCRUAL" <?= ($settings['accounting_basis'] ?? '') === 'ACCRUAL' ? 'selected' : '' ?>>Competenza</option><option value="CASH" <?= ($settings['accounting_basis'] ?? '') === 'CASH' ? 'selected' : '' ?>>Cassa</option></select></label>
<label class="field"><span>Periodicità IVA</span><select name="vat_periodicity"><option value="MONTHLY" <?= ($settings['vat_periodicity'] ?? '') === 'MONTHLY' ? 'selected' : '' ?>>Mensile</option><option value="QUARTERLY" <?= ($settings['vat_periodicity'] ?? '') === 'QUARTERLY' ? 'selected' : '' ?>>Trimestrale</option></select></label>
<label class="field"><span>Mese inizio esercizio</span><input type="number" min="1" max="12" name="fiscal_year_start_month" value="<?= (int) ($settings['fiscal_year_start_month'] ?? 1) ?>"></label>
<label class="field"><span>Pro-rata detraibilità %</span><input name="pro_rata_percent" inputmode="decimal" value="<?= View::e($settings['pro_rata_percent'] ?? '100') ?>"></label>
<label class="field"><span>Schema LIPE interno</span><input name="lipe_schema_version" value="<?= View::e($settings['lipe_schema_version'] ?? '2026-draft') ?>"></label>
<label class="field"><span>Schema IVA annuale interno</span><input name="vat_return_schema_version" value="<?= View::e($settings['vat_return_schema_version'] ?? 'IVA26-draft') ?>"></label>
<label class="checkbox-field"><input class="switch-input" type="checkbox" name="cash_vat_enabled" <?= !empty($settings['cash_vat_enabled']) ? 'checked' : '' ?>><span class="switch-ui"></span> IVA per cassa</label>
<label class="checkbox-field"><input class="switch-input" type="checkbox" name="auto_post_documents" <?= !isset($settings['auto_post_documents']) || !empty($settings['auto_post_documents']) ? 'checked' : '' ?>><span class="switch-ui"></span> Contabilizza documenti</label>
<label class="checkbox-field"><input class="switch-input" type="checkbox" name="auto_create_open_items" <?= !isset($settings['auto_create_open_items']) || !empty($settings['auto_create_open_items']) ? 'checked' : '' ?>><span class="switch-ui"></span> Crea partite</label>
</div><div class="form-actions"><button class="button primary" type="submit">Salva regole</button></div></form></section>

<section class="card" id="chart"><div class="card-header"><div><span class="section-kicker">Struttura centrale</span><h2>Piano dei conti</h2><p class="help">I conti di sistema sono protetti; la classificazione alimenta stato patrimoniale e conto economico.</p></div><span class="badge"><?= count($accounts) ?> conti</span></div>
<details class="setup-panel" <?= $selectedAccount ? 'open' : '' ?>><summary><span class="module-icon"><?= View::icon($selectedAccount ? 'settings' : 'plus') ?></span><span><strong><?= $selectedAccount ? 'Modifica ' . View::e($selectedAccount['code']) : 'Nuovo conto' ?></strong><small>Crea un conto movimentabile o un nodo di raggruppamento.</small></span><span class="setup-chevron">›</span></summary>
<form method="post" action="/accounting/setup/accounts" class="modern-form setup-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><?php if ($selectedAccount): ?><input type="hidden" name="id" value="<?= (int) $selectedAccount['id'] ?>"><?php endif; ?><div class="form-grid">
<label class="field"><span>Codice</span><input name="code" required maxlength="50" value="<?= View::e($selectedAccount['code'] ?? '') ?>"></label><label class="field"><span>Descrizione</span><input name="name" required value="<?= View::e($selectedAccount['name'] ?? '') ?>"></label>
<label class="field"><span>Tipo</span><select name="account_type"><?php foreach (['ASSET'=>'Attività','LIABILITY'=>'Passività','EQUITY'=>'Patrimonio netto','REVENUE'=>'Ricavo','EXPENSE'=>'Costo'] as $key=>$label): ?><option value="<?= $key ?>" <?= ($selectedAccount['account_type'] ?? 'ASSET') === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<label class="field"><span>Saldo naturale</span><select name="normal_balance"><option value="DEBIT" <?= ($selectedAccount['normal_balance'] ?? 'DEBIT') === 'DEBIT' ? 'selected' : '' ?>>Dare</option><option value="CREDIT" <?= ($selectedAccount['normal_balance'] ?? '') === 'CREDIT' ? 'selected' : '' ?>>Avere</option></select></label>
<label class="field"><span>Conto padre</span><select name="parent_id"><option value="">— Radice —</option><?php foreach ($accounts as $account): if ((int) $account['id'] === (int) ($selectedAccount['id'] ?? 0)) continue; ?><option value="<?= (int) $account['id'] ?>" <?= (int) ($selectedAccount['parent_id'] ?? 0) === (int) $account['id'] ? 'selected' : '' ?>><?= View::e($account['code'] . ' · ' . $account['name']) ?></option><?php endforeach; ?></select></label>
<label class="field"><span>Classificazione</span><input name="classification_code" placeholder="es. SP.ATTIVO.CREDITI" value="<?= View::e($selectedAccount['classification_code'] ?? '') ?>"></label><label class="field"><span>Sezione bilancio</span><input name="statement_section" placeholder="es. SP.ATTIVO.CREDITI" value="<?= View::e($selectedAccount['statement_section'] ?? '') ?>"></label><label class="field"><span>Codice fiscale</span><input name="tax_mapping_code" value="<?= View::e($selectedAccount['tax_mapping_code'] ?? '') ?>"></label>
<label class="checkbox-field"><input class="switch-input" type="checkbox" name="is_postable" <?= !$selectedAccount || !empty($selectedAccount['is_postable']) ? 'checked' : '' ?>><span class="switch-ui"></span> Movimentabile</label><label class="checkbox-field"><input class="switch-input" type="checkbox" name="active" <?= !$selectedAccount || !empty($selectedAccount['active']) ? 'checked' : '' ?>><span class="switch-ui"></span> Attivo</label><label class="checkbox-field"><input class="switch-input" type="checkbox" name="requires_party" <?= !empty($selectedAccount['requires_party']) ? 'checked' : '' ?>><span class="switch-ui"></span> Richiede anagrafica</label><label class="checkbox-field"><input class="switch-input" type="checkbox" name="requires_cost_center" <?= !empty($selectedAccount['requires_cost_center']) ? 'checked' : '' ?>><span class="switch-ui"></span> Richiede centro di costo</label>
</div><div class="form-actions"><?php if ($selectedAccount): ?><a class="button ghost" href="/accounting/setup#chart">Annulla modifica</a><?php endif; ?><button class="button primary" type="submit"><?= $selectedAccount ? 'Salva conto' : 'Crea conto' ?></button></div></form></details>
<div class="table-wrap"><table><thead><tr><th>Codice</th><th>Conto</th><th>Tipo</th><th>Padre</th><th>Classificazione</th><th>Movimenti</th><th>Stato</th><th></th></tr></thead><tbody><?php foreach ($accounts as $account): ?><tr><td class="primary-cell"><?= View::e($account['code']) ?></td><td><?= View::e($account['name']) ?><?= !empty($account['system_key']) ? '<small class="cell-subtitle">' . View::e($account['system_key']) . '</small>' : '' ?></td><td><?= View::e($account['account_type']) ?></td><td><?= View::e($account['parent_code'] ?? '—') ?></td><td><?= View::e($account['statement_section'] ?? '—') ?></td><td><?= (int) $account['movements'] ?></td><td><span class="badge status-<?= !empty($account['active']) ? 'active' : 'muted' ?>"><?= !empty($account['active']) ? 'ATTIVO' : 'DISATTIVO' ?></span></td><td><div class="row-actions"><a class="table-action" href="/accounting/setup?account_id=<?= (int) $account['id'] ?>#chart">Modifica</a><?php if (empty($account['locked'])): ?><form method="post" action="/accounting/setup/accounts/<?= (int) $account['id'] ?>/toggle"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="table-action" type="submit"><?= !empty($account['active']) ? 'Disattiva' : 'Attiva' ?></button></form><?php else: ?><span class="badge">PROTETTO</span><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div></section>

<section class="card" id="mappings"><div class="card-header"><div><span class="section-kicker">Scritture automatiche</span><h2>Collegamenti ai conti</h2></div></div><div class="mapping-grid">
<?php $byKey = []; foreach ($mappings as $mapping) { $byKey[$mapping['mapping_key']] = $mapping; } foreach ($mappingLabels as $key => $label): ?><form method="post" action="/accounting/setup/mappings" class="mapping-row"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><input type="hidden" name="mapping_key" value="<?= View::e($key) ?>"><label><strong><?= View::e($label) ?></strong><small><?= View::e($key) ?></small></label><select name="account_id" required><option value="">Seleziona conto…</option><?php foreach ($accounts as $account): if (empty($account['active']) || empty($account['is_postable'])) continue; ?><option value="<?= (int) $account['id'] ?>" <?= (int) ($byKey[$key]['account_id'] ?? 0) === (int) $account['id'] ? 'selected' : '' ?>><?= View::e($account['code'] . ' · ' . $account['name']) ?></option><?php endforeach; ?></select><button class="button" type="submit">Salva</button></form><?php endforeach; ?>
</div></section>

<div class="content-grid">
<section class="card span-5" id="registers"><div class="card-header"><div><span class="section-kicker">Protocollazione</span><h2>Sezionali IVA</h2></div></div><form method="post" action="/accounting/setup/registers" class="modern-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><div class="form-grid single-card-form"><label class="field"><span>Codice</span><input name="code" required></label><label class="field"><span>Nome</span><input name="name" required></label><label class="field"><span>Tipo</span><select name="register_type"><option value="SALES">Vendite</option><option value="PURCHASES">Acquisti</option><option value="CORRISPETTIVI">Corrispettivi</option></select></label><label class="field"><span>Prefisso</span><input name="prefix"></label><label class="field"><span>Prossimo protocollo</span><input type="number" min="1" name="next_protocol" value="1"></label><label class="checkbox-field"><input class="switch-input" type="checkbox" name="is_default"><span class="switch-ui"></span> Predefinito</label><input type="hidden" name="active" value="1"></div><div class="form-actions"><button class="button primary" type="submit">Aggiungi</button></div></form><div class="table-wrap"><table><thead><tr><th>Codice</th><th>Sezionale</th><th>Tipo</th><th>Protocollo</th></tr></thead><tbody><?php foreach ($registers as $register): ?><tr><td><?= View::e($register['code']) ?></td><td><?= View::e($register['name']) ?><?= !empty($register['is_default']) ? '<small class="cell-subtitle">Predefinito</small>' : '' ?></td><td><?= View::e($register['register_type']) ?></td><td><?= View::e($register['prefix']) ?><?= (int) $register['next_protocol'] ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="card span-7" id="causes"><div class="card-header"><div><span class="section-kicker">Prima nota</span><h2>Causali contabili</h2></div></div><form method="post" action="/accounting/setup/causes" class="modern-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><div class="form-grid"><label class="field"><span>Codice</span><input name="code" required></label><label class="field"><span>Nome</span><input name="name" required></label><label class="field"><span>Categoria</span><select name="category"><?php foreach (['GENERAL','SALES','PURCHASE','RECEIPT','PAYMENT','ADJUSTMENT','CLOSING','OPENING','DEPRECIATION','WITHHOLDING'] as $category): ?><option><?= $category ?></option><?php endforeach; ?></select></label><label class="field"><span>Sezionale IVA</span><select name="vat_register_id"><option value="">Nessuno</option><?php foreach ($registers as $register): ?><option value="<?= (int) $register['id'] ?>"><?= View::e($register['code'] . ' · ' . $register['name']) ?></option><?php endforeach; ?></select></label><label class="field full-width"><span>Descrizione predefinita</span><input name="default_description"></label><input type="hidden" name="active" value="1"></div><div class="form-actions"><button class="button primary" type="submit">Aggiungi</button></div></form><div class="table-wrap"><table><thead><tr><th>Codice</th><th>Causale</th><th>Categoria</th><th>Sezionale</th><th>Automatica</th></tr></thead><tbody><?php foreach ($causes as $cause): ?><tr><td><?= View::e($cause['code']) ?></td><td><?= View::e($cause['name']) ?></td><td><?= View::e($cause['category']) ?></td><td><?= View::e($cause['register_code'] ?? '—') ?></td><td><?= !empty($cause['automatic']) ? 'Sì' : 'No' ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
