<?php
use Luna\Core\View;
$baseQuery = ['party_type' => $type, 'from' => $from, 'to' => $to, 'q' => $search];
$exportQuery = http_build_query(array_filter($baseQuery + ['party_id' => $partyId ?: null]));
$isSupplier = $type === 'SUPPLIER';
?>
<section class="page-intro compact"><div><span class="eyebrow">Contabilità analitica</span><h1>Partitario clienti e fornitori</h1><p>Ogni anagrafica è un sottoconto del relativo conto collettivo. Consulta fatture, note di credito, pagamenti e saldo progressivo.</p></div><a class="button ghost" href="/accounting/treasury">Tesoreria e partite</a></section>

<nav class="accounting-tabs party-ledger-tabs">
    <a class="<?= $isSupplier ? 'active' : '' ?>" href="/accounting/subledgers?<?= View::e(http_build_query(['party_type' => 'SUPPLIER', 'from' => $from, 'to' => $to])) ?>">Fornitori</a>
    <a class="<?= !$isSupplier ? 'active' : '' ?>" href="/accounting/subledgers?<?= View::e(http_build_query(['party_type' => 'CUSTOMER', 'from' => $from, 'to' => $to])) ?>">Clienti</a>
</nav>

<section class="filter-toolbar-card"><form method="get" class="party-ledger-filter"><input type="hidden" name="party_type" value="<?= View::e($type) ?>"><label class="field"><span>Cerca sottoconto</span><span class="search-control"><?= View::icon('search') ?><input type="search" name="q" value="<?= View::e($search) ?>" placeholder="Codice, ragione sociale o Partita IVA…" autocomplete="off"></span></label><label class="field"><span>Dal</span><input type="date" name="from" value="<?= View::e($from) ?>"></label><label class="field"><span>Al</span><input type="date" name="to" value="<?= View::e($to) ?>"></label><div class="filter-submit-actions"><button class="button primary" type="submit">Filtra</button><a class="button ghost" href="/accounting/subledgers?party_type=<?= View::e($type) ?>">Azzera</a></div></form></section>

<section class="accounting-kpis party-ledger-kpis"><article><span>Sottoconti</span><strong><?= count($parties) ?></strong><small>Tutte le anagrafiche trovate</small></article><article><span>Dare nel periodo</span><strong><?= View::money($totals['debit']) ?></strong></article><article><span>Avere nel periodo</span><strong><?= View::money($totals['credit']) ?></strong></article><article><span><?= $isSupplier ? 'Saldo fornitori' : 'Saldo clienti' ?></span><strong><?= View::money($totals['balance']) ?></strong></article><article><span><?= $isSupplier ? 'Ancora da pagare' : 'Ancora da incassare' ?></span><strong><?= View::money($totals['outstanding']) ?></strong><small>Partite aperte alla data odierna</small></article></section>

<section class="card data-card"><div class="card-header"><div><span class="section-kicker"><?= $isSupplier ? 'Conto collettivo fornitori' : 'Conto collettivo clienti' ?></span><h2>Sottoconti <?= $isSupplier ? 'fornitori' : 'clienti' ?></h2><p class="help">Il saldo include tutte le scritture collegate all’anagrafica; il residuo deriva dalle partite ancora aperte.</p></div><div class="export-actions"><a class="button ghost" href="/accounting/subledgers/export/pdf?<?= View::e($exportQuery) ?>">PDF</a><a class="button ghost" href="/accounting/subledgers/export/xlsx?<?= View::e($exportQuery) ?>">XLSX</a><a class="button ghost" href="/accounting/subledgers/export/csv?<?= View::e($exportQuery) ?>">CSV</a></div></div><div class="table-wrap"><table><thead><tr><th>Sottoconto</th><th>Ragione sociale</th><th>Partita IVA</th><th class="numeric">Saldo iniziale</th><th class="numeric">Dare</th><th class="numeric">Avere</th><th class="numeric">Saldo finale</th><th class="numeric"><?= $isSupplier ? 'Da pagare' : 'Da incassare' ?></th></tr></thead><tbody><?php foreach ($parties as $party): $query = http_build_query(array_filter($baseQuery + ['party_id' => $party['id']])); ?><tr class="<?= $partyId === (int) $party['id'] ? 'selected-row' : '' ?>"><td class="primary-cell"><a href="/accounting/subledgers?<?= View::e($query) ?>"><?= View::e($party['code']) ?></a></td><td><a href="/accounting/subledgers?<?= View::e($query) ?>"><?= View::e($party['business_name']) ?></a><?= empty($party['active']) ? '<small class="cell-subtitle">Anagrafica disattivata</small>' : '' ?></td><td><?= View::e($party['vat_number'] ?: '—') ?></td><td class="numeric"><?= View::money($party['opening_balance']) ?></td><td class="numeric"><?= View::money($party['period_debit']) ?></td><td class="numeric"><?= View::money($party['period_credit']) ?></td><td class="numeric"><strong><?= View::money($party['closing_balance']) ?></strong></td><td class="numeric"><strong><?= View::money($party['outstanding']) ?></strong><?php if ((int) $party['open_count'] > 0): ?><small class="cell-subtitle"><?= (int) $party['open_count'] ?> partite</small><?php endif; ?></td></tr><?php endforeach; ?><?php if (!$parties): ?><tr><td colspan="8"><div class="table-empty"><strong>Nessun sottoconto trovato</strong><small>Modifica la ricerca oppure importa le anagrafiche clienti e fornitori.</small></div></td></tr><?php endif; ?></tbody><tfoot><tr><th colspan="4">Totali periodo</th><th class="numeric"><?= View::money($totals['debit']) ?></th><th class="numeric"><?= View::money($totals['credit']) ?></th><th class="numeric"><?= View::money($totals['balance']) ?></th><th class="numeric"><?= View::money($totals['outstanding']) ?></th></tr></tfoot></table></div></section>

<?php if ($detail): $party = $detail['party']; $detailTotals = $detail['totals']; ?>
<section class="card subledger-detail" id="scheda"><div class="card-header"><div><span class="section-kicker">Scheda analitica · <?= View::e($party['code']) ?></span><h2><?= View::e($party['business_name']) ?></h2><p class="help"><?= View::e($party['vat_number'] ? 'P.IVA ' . $party['vat_number'] : 'Partita IVA non indicata') ?> · <?= View::e(trim(implode(' ', array_filter([$party['address'] ?? '', $party['postal_code'] ?? '', $party['city'] ?? ''])))) ?></p></div><a class="button ghost" href="/accounting/subledgers?<?= View::e(http_build_query($baseQuery)) ?>">Chiudi scheda</a></div>
<div class="statement-summary"><article><span>Saldo iniziale</span><strong><?= View::money($detailTotals['opening']) ?></strong></article><article><span>Dare</span><strong><?= View::money($detailTotals['debit']) ?></strong></article><article><span>Avere</span><strong><?= View::money($detailTotals['credit']) ?></strong></article><article><span>Saldo finale</span><strong><?= View::money($detailTotals['closing']) ?></strong></article><article><span><?= $isSupplier ? 'Da pagare' : 'Da incassare' ?></span><strong><?= View::money($detailTotals['outstanding']) ?></strong></article></div>
<div class="subledger-section-head"><div><span class="section-kicker">Movimenti contabili</span><h3>Estratto del sottoconto</h3></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Protocollo</th><th>Documento</th><th>Descrizione</th><th class="numeric">Dare</th><th class="numeric">Avere</th><th class="numeric">Saldo progressivo</th></tr></thead><tbody><?php foreach ($detail['rows'] as $row): ?><tr><td><?= View::date($row['entry_date']) ?></td><td class="primary-cell"><a href="/accounting/journal/<?= (int) $row['entry_id'] ?>"><?= View::e($row['protocol_number']) ?></a><small class="cell-subtitle"><?= View::e($row['source_protocol'] ?: '') ?></small></td><td><?= View::e($row['document_number'] ?: '—') ?></td><td><?= View::e($row['description'] ?: $row['entry_description']) ?></td><td class="numeric"><?= View::money($row['debit']) ?></td><td class="numeric"><?= View::money($row['credit']) ?></td><td class="numeric"><strong><?= View::money($row['running_balance']) ?></strong></td></tr><?php endforeach; ?><?php if (!$detail['rows']): ?><tr><td colspan="7" class="muted">Nessun movimento contabile collegato nel periodo selezionato.</td></tr><?php endif; ?></tbody></table></div>
<div class="subledger-section-head"><div><span class="section-kicker">Scadenzario</span><h3>Fatture, note di credito e pagamenti</h3></div></div><div class="table-wrap"><table><thead><tr><th>Documento</th><th>Tipo</th><th>Emissione</th><th>Scadenza</th><th class="numeric">Originario</th><th class="numeric">Pagato</th><th class="numeric">Residuo</th><th>Stato</th></tr></thead><tbody><?php foreach ($detail['open_items'] as $item): ?><tr><td class="primary-cell"><?php if ($item['document_id']): ?><a href="/documents/<?= $isSupplier ? 'purchase-invoices' : 'invoices' ?>/<?= (int) $item['document_id'] ?>"><?= View::e($item['reference'] ?: 'Documento') ?></a><?php else: ?><?= View::e($item['reference'] ?: '—') ?><?php endif; ?></td><td><?= View::e($item['direction'] === ($isSupplier ? 'PAYABLE' : 'RECEIVABLE') ? 'Fattura' : 'Nota di credito') ?></td><td><?= View::date($item['issue_date']) ?></td><td><?= View::date($item['due_date']) ?></td><td class="numeric"><?= View::money($item['original_amount']) ?></td><td class="numeric"><?= View::money($item['settled_amount']) ?></td><td class="numeric"><strong><?= View::money($item['signed_outstanding']) ?></strong></td><td><span class="badge status-<?= View::e(strtolower((string) $item['status'])) ?>"><?= View::e(View::label($item['status'])) ?></span></td></tr><?php endforeach; ?><?php if (!$detail['open_items']): ?><tr><td colspan="8" class="muted">Nessuna partita associata a questa anagrafica.</td></tr><?php endif; ?></tbody></table></div></section>
<?php endif; ?>
