<?php use Luna\Core\Csrf; use Luna\Core\View; ?>
<section class="page-intro compact"><div><a class="back-link" href="/accounting/vat-settlements?year=<?= (int) $settlement['period_year'] ?>">← Liquidazioni IVA</a><span class="eyebrow"><?= $settlement['period_type'] === 'MONTHLY' ? 'Liquidazione mensile' : 'Liquidazione trimestrale' ?></span><h1>Periodo <?= (int) $settlement['period_number'] ?> · <?= (int) $settlement['period_year'] ?></h1><p>Calcolata il <?= View::date($settlement['calculated_at'] ?: $settlement['updated_at']) ?></p></div><span class="badge status-<?= strtolower((string) $settlement['status']) ?> settlement-status"><?= View::e($settlement['status']) ?></span></section>

<section class="accounting-kpis settlement-kpis"><article><span>IVA a debito</span><strong><?= View::money($settlement['vat_debit']) ?></strong></article><article><span>IVA detraibile</span><strong><?= View::money($settlement['vat_credit']) ?></strong></article><article><span>Credito precedente</span><strong><?= View::money($settlement['previous_credit']) ?></strong></article><article><span>Interessi</span><strong><?= View::money($settlement['interest_amount']) ?></strong></article><article class="<?= (float) $settlement['balance'] > 0 ? 'attention' : '' ?>"><span><?= (float) $settlement['balance'] >= 0 ? 'IVA da versare' : 'Credito da riportare' ?></span><strong><?= View::money(abs((float) $settlement['balance'])) ?></strong></article></section>

<section class="card data-card"><div class="card-header"><div><span class="section-kicker">Prospetto di calcolo</span><h2>Dettaglio per registro, articolo e aliquota IVA</h2></div><div class="export-actions"><a class="button ghost" href="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/export/pdf">PDF</a><a class="button ghost" href="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/export/xlsx">XLSX</a><a class="button ghost" href="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/export/csv">CSV</a></div></div><div class="table-wrap"><table><thead><tr><th>Registro</th><th>Codice / articolo IVA</th><th>Aliquota</th><th>Natura / riferimento</th><th class="numeric">Imponibile</th><th class="numeric">IVA</th><th class="numeric">IVA detraibile</th></tr></thead><tbody><?php foreach ($details as $detail): ?><tr><td><?= match ($detail['register_type']) { 'SALES' => 'Vendite', 'PURCHASES' => 'Acquisti', 'CORRISPETTIVI' => 'Corrispettivi', default => View::e($detail['register_type']) } ?></td><td><span class="badge"><?= View::e($detail['vat_code']) ?></span><small class="cell-subtitle"><?= View::e($detail['vat_description']) ?></small></td><td class="numeric"><?= number_format((float) $detail['vat_rate'], 2, ',', '.') ?>%</td><td><?= View::e($detail['vat_nature'] ?: '—') ?><small class="cell-subtitle"><?= View::e($detail['vat_legal_reference'] ?: '') ?></small></td><td class="numeric"><?= View::money($detail['taxable_amount']) ?></td><td class="numeric"><?= View::money($detail['vat_amount']) ?></td><td class="numeric"><?= View::money($detail['deductible_vat']) ?></td></tr><?php endforeach; ?><?php if (!$details): ?><tr><td colspan="7" class="muted">Nessun movimento IVA nel periodo.</td></tr><?php endif; ?></tbody><tfoot><tr><th colspan="4">Totali per articolo e aliquota</th><th class="numeric"><?= View::money(array_sum(array_column($details, 'taxable_amount'))) ?></th><th class="numeric"><?= View::money(array_sum(array_column($details, 'vat_amount'))) ?></th><th class="numeric"><?= View::money(array_sum(array_column($details, 'deductible_vat'))) ?></th></tr><tr><th colspan="4">Risultato liquidazione</th><th colspan="3" class="numeric"><?= View::money($settlement['balance']) ?></th></tr></tfoot></table></div></section>

<?php if ($settlement['notes']): ?><section class="card accounting-note"><span class="section-kicker">Note</span><p><?= nl2br(View::e($settlement['notes'])) ?></p></section><?php endif; ?>

<section class="card settlement-actions"><div><span class="section-kicker">Workflow</span><h2>Stato liquidazione</h2><p>Una liquidazione definitiva o pagata blocca le modifiche ai movimenti IVA del periodo.</p></div><div class="inline-actions">
<?php if ($settlement['status'] === 'CALCULATED'): ?><form method="post" action="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/status" data-confirm="Rendere definitiva la liquidazione e bloccare il periodo?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><input type="hidden" name="status" value="SUBMITTED"><button class="button primary" type="submit"><?= View::icon('check') ?> Rendi definitiva</button></form><?php endif; ?>
<?php if ($settlement['status'] === 'SUBMITTED'): ?><form method="post" action="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/status" class="inline-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><input type="hidden" name="status" value="PAID"><label>Data pagamento <input type="date" name="payment_date" value="<?= date('Y-m-d') ?>" required></label><button class="button primary" type="submit">Segna pagata</button></form><?php endif; ?>
<?php if (in_array($settlement['status'], ['SUBMITTED','PAID'], true)): ?><form method="post" action="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/status" data-confirm="Riaprire il periodo IVA e consentire nuove modifiche?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><input type="hidden" name="status" value="CALCULATED"><button class="button ghost" type="submit">Riapri periodo</button></form><?php endif; ?>
</div></section>
