<?php
use Luna\Core\Csrf;
use Luna\Core\View;
$registerLabels = ['SALES' => 'Vendite', 'PURCHASES' => 'Acquisti', 'CORRISPETTIVI' => 'Corrispettivi'];
$monthLabels = [1=>'Gennaio',2=>'Febbraio',3=>'Marzo',4=>'Aprile',5=>'Maggio',6=>'Giugno',7=>'Luglio',8=>'Agosto',9=>'Settembre',10=>'Ottobre',11=>'Novembre',12=>'Dicembre'];
?>
<section class="page-intro compact"><div><span class="eyebrow">Contabilità IVA</span><h1>Registri IVA</h1><p>Movimenti di vendite, acquisti e corrispettivi, riepilogati per codice IVA.</p></div><div class="inline-actions"><a class="button ghost" href="/accounting/vat-settlements">Liquidazioni IVA</a><form method="post" action="/accounting/vat-registers/sync"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="button primary" type="submit"><?= View::icon('check') ?> Sincronizza documenti</button></form></div></section>

<nav class="accounting-tabs" aria-label="Registri IVA"><?php foreach ($registerLabels as $key => $label): ?><a class="<?= $register === $key ? 'active' : '' ?>" href="/accounting/vat-registers?register=<?= View::e($key) ?>&year=<?= $year ?>&month=<?= $month ?>"><?= View::e($label) ?></a><?php endforeach; ?></nav>

<section class="accounting-kpis"><article><span>Righe registro</span><strong><?= count($movements) ?></strong></article><article><span>Imponibile</span><strong><?= View::money($totals['taxable']) ?></strong></article><article><span>IVA</span><strong><?= View::money($totals['vat']) ?></strong></article><article><span>IVA detraibile</span><strong><?= View::money($totals['deductible']) ?></strong></article></section>

<section class="list-toolbar accounting-toolbar"><form method="get" class="search-form filter-form"><input type="hidden" name="register" value="<?= View::e($register) ?>"><label>Anno <input type="number" name="year" min="2000" max="2200" value="<?= $year ?>"></label><label>Mese <select name="month"><?php foreach ($monthLabels as $number => $label): ?><option value="<?= $number ?>" <?= $month === $number ? 'selected' : '' ?>><?= View::e($label) ?></option><?php endforeach; ?></select></label><button class="button" type="submit">Visualizza</button></form><span class="period-label"><?= View::e($registerLabels[$register]) ?> · <?= View::e($monthLabels[$month]) ?> <?= $year ?></span></section>

<div class="content-grid vat-grid">
<section class="card data-card span-7"><div class="card-header"><div><span class="section-kicker">Registro <?= View::e(mb_strtolower($registerLabels[$register])) ?></span><h2>Movimenti del periodo</h2></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Protocollo</th><th>Controparte</th><th>Codice IVA</th><th>Imponibile</th><th>IVA</th><th>Detraibile</th><th>Origine</th><th></th></tr></thead><tbody>
<?php foreach ($movements as $movement): ?><tr><td><?= View::date($movement['movement_date']) ?></td><td><?= View::e($movement['protocol_number'] ?: '—') ?></td><td class="primary-cell"><?= View::e($movement['counterparty_name'] ?: $movement['description'] ?: '—') ?><small><?= View::e($movement['description'] ?: '') ?></small></td><td><span class="badge"><?= View::e($movement['vat_code']) ?></span></td><td><?= View::money($movement['taxable_amount']) ?></td><td><?= View::money($movement['vat_amount']) ?></td><td><?= View::money($movement['deductible_vat']) ?></td><td><?= $movement['source_type'] === 'DOCUMENT' ? 'Documento' : 'Manuale' ?></td><td class="row-actions"><?php if ($movement['source_type'] === 'MANUAL' && !$movement['document_id']): ?><form method="post" action="/accounting/vat-registers/<?= (int) $movement['id'] ?>/delete" data-confirm="Eliminare il movimento IVA manuale?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="table-action danger-text" type="submit">Elimina</button></form><?php endif; ?></td></tr><?php endforeach; ?>
<?php if (!$movements): ?><tr><td colspan="9"><div class="table-empty"><span><?= View::icon('receipt') ?></span><strong>Registro vuoto</strong><small>Sincronizza i documenti emessi/ricevuti o inserisci un movimento manuale.</small></div></td></tr><?php endif; ?></tbody></table></div></section>

<section class="card settings-card span-5 vat-summary"><div class="card-header"><div><span class="section-kicker">Riepilogo aliquote</span><h2>Totali per codice IVA</h2></div><span class="score"><?= count($summary) ?></span></div><div class="table-wrap"><table><thead><tr><th>Codice</th><th>Imponibile</th><th>IVA</th><th>Detraibile</th></tr></thead><tbody><?php foreach ($summary as $row): ?><tr><td><span class="badge"><?= View::e($row['vat_code']) ?></span></td><td><?= View::money($row['taxable_amount']) ?></td><td><?= View::money($row['vat_amount']) ?></td><td><?= View::money($row['deductible_vat']) ?></td></tr><?php endforeach; ?><?php if (!$summary): ?><tr><td colspan="4" class="muted">Nessun totale disponibile.</td></tr><?php endif; ?></tbody></table></div></section>
</div>

<details class="card setup-panel vat-manual-panel"><summary><span class="module-icon"><?= View::icon('plus') ?></span><span><strong>Inserisci movimento IVA manuale</strong><small>Per corrispettivi, rettifiche e dati storici non collegati a un documento Luna2.</small></span><?= View::icon('chevron', 'setup-chevron') ?></summary><form method="post" action="/accounting/vat-registers/manual" class="modern-form setup-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><div class="form-grid">
<label class="field"><span>Registro *</span><select name="register_type" required><?php foreach ($registerLabels as $key => $label): ?><option value="<?= View::e($key) ?>" <?= $register === $key ? 'selected' : '' ?>><?= View::e($label) ?></option><?php endforeach; ?></select></label><label class="field"><span>Data *</span><input type="date" name="movement_date" value="<?= sprintf('%04d-%02d-01', $year, $month) ?>" required></label><label class="field"><span>Protocollo</span><input name="protocol_number"></label><label class="field"><span>Controparte</span><input name="counterparty_name"></label><label class="field"><span>Codice IVA *</span><input name="vat_code" list="vat-code-list" required><datalist id="vat-code-list"><?php foreach ($vatCodes as $code): ?><option value="<?= View::e($code['code']) ?>"><?= View::e($code['description']) ?></option><?php endforeach; ?></datalist></label><label class="field"><span>Descrizione</span><input name="description"></label><label class="field"><span>Imponibile *</span><input name="taxable_amount" inputmode="decimal" required></label><label class="field"><span>IVA *</span><input name="vat_amount" inputmode="decimal" required></label><label class="field"><span>IVA detraibile</span><input name="deductible_vat" inputmode="decimal"><small>Compilare per il registro acquisti; può essere inferiore all’IVA in caso di indetraibilità.</small></label>
</div><div class="form-actions"><button class="button primary" type="submit"><?= View::icon('check') ?> Registra movimento</button></div></form></details>
