<?php use Luna\Core\Csrf; use Luna\Core\View; ?>
<section class="page-intro compact"><div><span class="eyebrow">Contabilità IVA</span><h1>Liquidazioni IVA</h1><p>Calcolo periodico basato sui registri vendite, acquisti e corrispettivi.</p></div><div class="inline-actions"><a class="button ghost" href="/accounting/vat-registers">Registri IVA</a><a class="button ghost" href="/accounting/journal">Prima nota</a></div></section>

<div class="system-banner neutral-banner"><span class="system-banner-icon"><?= View::icon('alert') ?></span><div><strong>Controllo professionale richiesto</strong><span>Credito precedente, interessi trimestrali, pro-rata e regimi speciali devono essere verificati dal responsabile contabile prima di rendere definitiva la liquidazione.</span></div></div>

<div class="content-grid settlement-grid">
<section class="card settings-card span-5"><div class="card-header"><div><span class="section-kicker">Nuovo calcolo</span><h2>Calcola liquidazione</h2></div><?= View::icon('calculator') ?></div><form method="post" action="/accounting/vat-settlements/calculate" class="modern-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><div class="form-grid settlement-form">
<label class="field"><span>Periodicità</span><select name="period_type"><option value="MONTHLY">Mensile</option><option value="QUARTERLY">Trimestrale</option></select></label><label class="field"><span>Anno</span><input type="number" name="period_year" min="2000" max="2200" value="<?= $year ?>" required></label><label class="field"><span>Numero periodo</span><input type="number" name="period_number" min="1" max="12" value="<?= (int) date('n') ?>" required><small>1–12 per mensile, 1–4 per trimestrale.</small></label><label class="field"><span>Credito precedente</span><input name="previous_credit" inputmode="decimal" value="0"></label><label class="field"><span>Interessi</span><input name="interest_amount" inputmode="decimal" value="0"><small>Inserire l’importo verificato, senza automatismi normativi.</small></label><label class="field"><span>Scadenza pagamento</span><input type="date" name="payment_due_date"></label><label class="field full-width"><span>Note</span><textarea name="notes" rows="3"></textarea></label></div><div class="form-actions"><button class="button primary" type="submit"><?= View::icon('check') ?> Calcola e salva</button></div></form></section>

<section class="card data-card span-7"><div class="card-header"><div><span class="section-kicker">Esercizio <?= $year ?></span><h2>Liquidazioni calcolate</h2></div><form method="get" class="inline-form"><label>Anno <input type="number" name="year" min="2000" max="2200" value="<?= $year ?>"></label><button class="button" type="submit">Vai</button></form></div><div class="table-wrap"><table><thead><tr><th>Periodo</th><th>IVA a debito</th><th>IVA detraibile</th><th>Credito prec.</th><th>Interessi</th><th>Saldo</th><th>Stato</th><th></th></tr></thead><tbody>
<?php foreach ($settlements as $settlement): ?><tr><td class="primary-cell"><?= $settlement['period_type'] === 'MONTHLY' ? 'Mese ' : 'Trimestre ' ?><?= (int) $settlement['period_number'] ?><small><?= View::e($settlement['period_type']) ?></small></td><td><?= View::money($settlement['vat_debit']) ?></td><td><?= View::money($settlement['vat_credit']) ?></td><td><?= View::money($settlement['previous_credit']) ?></td><td><?= View::money($settlement['interest_amount']) ?></td><td class="<?= (float) $settlement['balance'] > 0 ? 'danger-text' : '' ?>"><?= View::money($settlement['balance']) ?></td><td><span class="badge status-<?= strtolower((string) $settlement['status']) ?>"><?= View::e($settlement['status']) ?></span></td><td><a class="table-action" href="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>">Apri</a></td></tr><?php endforeach; ?>
<?php if (!$settlements): ?><tr><td colspan="8"><div class="table-empty"><span><?= View::icon('calculator') ?></span><strong>Nessuna liquidazione</strong><small>Verifica prima i registri IVA e calcola il periodo.</small></div></td></tr><?php endif; ?></tbody></table></div></section>
</div>
