<?php
use Luna\Core\Csrf;
use Luna\Core\View;
$registerLabels = ['SALES' => 'Vendite', 'PURCHASES' => 'Acquisti', 'CORRISPETTIVI' => 'Corrispettivi', 'REVERSE_CHARGE' => 'Reverse charge', 'SELF_INVOICES' => 'Autofatture'];
$entryRegisterLabels = array_intersect_key($registerLabels, array_flip(['SALES', 'PURCHASES', 'CORRISPETTIVI']));
$monthLabels = [1=>'Gennaio',2=>'Febbraio',3=>'Marzo',4=>'Aprile',5=>'Maggio',6=>'Giugno',7=>'Luglio',8=>'Agosto',9=>'Settembre',10=>'Ottobre',11=>'Novembre',12=>'Dicembre'];
$exportQuery = http_build_query(array_filter(['register'=>$register,'year'=>$year,'month'=>$month,'q'=>$search]));
?>
<section class="page-intro compact"><div><span class="eyebrow">Contabilità IVA</span><h1>Registri IVA</h1><p>Vendite, acquisti, reverse charge, autofatture e corrispettivi con totali per articolo e aliquota IVA.</p></div><div class="inline-actions"><a class="button ghost" href="/accounting/vat-settlements">Liquidazioni IVA</a><form method="post" action="/accounting/vat-registers/sync"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="button primary" type="submit"><?= View::icon('check') ?> Sincronizza documenti</button></form></div></section>

<nav class="accounting-tabs" aria-label="Registri IVA"><?php foreach ($registerLabels as $key => $label): ?><a class="<?= $register === $key ? 'active' : '' ?>" href="/accounting/vat-registers?register=<?= View::e($key) ?>&year=<?= $year ?>&month=<?= $month ?>"><?= View::e($label) ?></a><?php endforeach; ?></nav>

<section class="accounting-kpis"><article><span>Righe registro</span><strong><?= count($movements) ?></strong></article><article><span>Imponibile</span><strong><?= View::money($totals['taxable']) ?></strong></article><article><span>IVA</span><strong><?= View::money($totals['vat']) ?></strong></article><article><span>IVA detraibile</span><strong><?= View::money($totals['deductible']) ?></strong></article></section>

<section class="list-toolbar accounting-toolbar"><form method="get" class="search-form filter-form"><input type="hidden" name="register" value="<?= View::e($register) ?>"><label>Anno <input type="number" name="year" min="2000" max="2200" value="<?= $year ?>"></label><label>Mese <select name="month"><?php foreach ($monthLabels as $number => $label): ?><option value="<?= $number ?>" <?= $month === $number ? 'selected' : '' ?>><?= View::e($label) ?></option><?php endforeach; ?></select></label><button class="button" type="submit">Visualizza</button></form><span class="period-label"><?= View::e($registerLabels[$register]) ?> · <?= View::e($monthLabels[$month]) ?> <?= $year ?></span></section>

<section class="list-toolbar exportable-toolbar">
    <form method="get" class="search-form"><input type="hidden" name="register" value="<?= View::e($register) ?>"><input type="hidden" name="year" value="<?= $year ?>"><input type="hidden" name="month" value="<?= $month ?>"><span class="search-control"><?= View::icon('search') ?><input type="search" name="q" value="<?= View::e($search) ?>" placeholder="Protocollo, controparte, codice IVA…"></span><button class="button">Cerca</button></form>
    <div class="export-actions"><a class="button ghost" href="/accounting/vat-registers/export/pdf?<?= View::e($exportQuery) ?>">PDF</a><a class="button ghost" href="/accounting/vat-registers/export/xlsx?<?= View::e($exportQuery) ?>">XLSX</a><a class="button ghost" href="/accounting/vat-registers/export/csv?<?= View::e($exportQuery) ?>">CSV</a></div>
</section>
<div class="content-grid vat-grid">
<section class="card data-card span-7"><div class="card-header"><div><span class="section-kicker">Registro <?= View::e(mb_strtolower($registerLabels[$register])) ?></span><h2>Movimenti del periodo</h2></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Protocollo</th><th>Controparte</th><th>Codice IVA</th><th>Regime</th><th>Imponibile</th><th>IVA</th><th>Dovuta</th><th>Detraibile</th><th>Origine</th><th></th></tr></thead><tbody>
<?php foreach ($movements as $movement): ?><tr><td><?= View::date($movement['movement_date']) ?></td><td><?= View::e($movement['protocol_number'] ?: '—') ?></td><td class="primary-cell"><?= View::e($movement['counterparty_name'] ?: $movement['description'] ?: '—') ?><small><?= View::e($movement['description'] ?: '') ?></small></td><td><span class="badge"><?= View::e($movement['vat_code']) ?></span></td><td><?= View::e($movement['operation_type']) ?><small class="cell-subtitle"><?= View::e($movement['collectability']) ?></small></td><td><?= View::money($movement['taxable_amount']) ?></td><td><?= View::money($movement['vat_amount']) ?></td><td><?= View::money($movement['vat_due_amount']) ?></td><td><?= View::money($movement['deductible_vat']) ?><small class="cell-subtitle"><?= View::e($movement['deductibility_percent']) ?>%</small></td><td><?= $movement['source_type'] === 'DOCUMENT' ? 'Documento' : 'Manuale' ?></td><td class="row-actions"><?php if ($movement['source_type'] === 'MANUAL' && !$movement['document_id']): ?><form method="post" action="/accounting/vat-registers/<?= (int) $movement['id'] ?>/delete" data-confirm="Eliminare il movimento IVA manuale?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><button class="table-action danger-text" type="submit">Elimina</button></form><?php endif; ?></td></tr><?php endforeach; ?>
<?php if (!$movements): ?><tr><td colspan="11"><div class="table-empty"><span><?= View::icon('receipt') ?></span><strong>Registro vuoto</strong><small>Sincronizza i documenti emessi/ricevuti o inserisci un movimento manuale.</small></div></td></tr><?php endif; ?></tbody></table></div></section>

<section class="card settings-card span-5 vat-summary"><div class="card-header"><div><span class="section-kicker">Riepilogo aliquote</span><h2>Totali per articolo e aliquota IVA</h2></div><span class="score"><?= count($summary) ?></span></div><div class="table-wrap"><table><thead><tr><th>Codice / articolo</th><th>Aliquota</th><th>Imponibile</th><th>IVA</th><th>Dovuta</th><th>Detraibile</th></tr></thead><tbody><?php foreach ($summary as $row): ?><tr><td><span class="badge"><?= View::e($row['vat_code']) ?></span><small class="cell-subtitle"><?= View::e($row['vat_description']) ?><?= $row['vat_nature'] ? ' · ' . View::e($row['vat_nature']) : '' ?><?= $row['vat_legal_reference'] ? ' · ' . View::e($row['vat_legal_reference']) : '' ?></small></td><td class="numeric"><?= number_format((float) $row['vat_rate'], 2, ',', '.') ?>%</td><td class="numeric"><?= View::money($row['taxable_amount']) ?></td><td class="numeric"><?= View::money($row['vat_amount']) ?></td><td class="numeric"><?= View::money($row['vat_due_amount']) ?></td><td class="numeric"><?= View::money($row['deductible_vat']) ?></td></tr><?php endforeach; ?><?php if (!$summary): ?><tr><td colspan="6" class="muted">Nessun totale disponibile.</td></tr><?php endif; ?></tbody><tfoot><tr><th colspan="2">Totali registro</th><th class="numeric"><?= View::money(array_sum(array_column($summary, 'taxable_amount'))) ?></th><th class="numeric"><?= View::money(array_sum(array_column($summary, 'vat_amount'))) ?></th><th class="numeric"><?= View::money(array_sum(array_column($summary, 'vat_due_amount'))) ?></th><th class="numeric"><?= View::money(array_sum(array_column($summary, 'deductible_vat'))) ?></th></tr></tfoot></table></div></section>
</div>

<details class="card setup-panel vat-manual-panel"><summary><span class="module-icon"><?= View::icon('plus') ?></span><span><strong>Inserisci movimento IVA manuale</strong><small>Per corrispettivi, rettifiche e dati storici non collegati a un documento Luna2.</small></span><?= View::icon('chevron', 'setup-chevron') ?></summary><form method="post" action="/accounting/vat-registers/manual" class="modern-form setup-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><div class="form-grid">
<label class="field"><span>Registro *</span><select name="register_type" required><?php foreach ($entryRegisterLabels as $key => $label): ?><option value="<?= View::e($key) ?>" <?= $register === $key ? 'selected' : '' ?>><?= View::e($label) ?></option><?php endforeach; ?></select></label><label class="field"><span>Sezionale</span><select name="vat_register_id"><option value="">Predefinito</option><?php foreach (($registers ?? []) as $section): ?><option value="<?= (int) $section['id'] ?>"><?= View::e($section['code'] . ' · ' . $section['name']) ?></option><?php endforeach; ?></select></label><label class="field"><span>Data *</span><input type="date" name="movement_date" value="<?= sprintf('%04d-%02d-01', $year, $month) ?>" required></label><label class="field"><span>Operazione</span><select name="operation_type"><?php foreach (['DOMESTIC','REVERSE_CHARGE','SPLIT_PAYMENT','CASH','INTRA_EU','EXTRA_EU','MARGIN','EXEMPT','NON_TAXABLE','ADJUSTMENT'] as $operation): ?><option><?= $operation ?></option><?php endforeach; ?></select></label><label class="field"><span>Esigibilità</span><select name="collectability"><option>IMMEDIATE</option><option>DEFERRED</option><option>SPLIT</option><option>CASH</option></select></label><label class="field"><span>Protocollo</span><input name="protocol_number"></label><label class="field"><span>Controparte</span><input name="counterparty_name"></label><label class="field"><span>Codice IVA *</span><input name="vat_code" list="vat-code-list" required><datalist id="vat-code-list"><?php foreach ($vatCodes as $code): ?><option value="<?= View::e($code['code']) ?>"><?= View::e($code['description']) ?></option><?php endforeach; ?></datalist></label><label class="field"><span>Descrizione</span><input name="description"></label><label class="field"><span>Imponibile *</span><input name="taxable_amount" inputmode="decimal" required></label><label class="field"><span>IVA *</span><input name="vat_amount" inputmode="decimal" required></label><label class="field"><span>IVA dovuta</span><input name="vat_due_amount" inputmode="decimal"><small>Utile per reverse charge e rettifiche.</small></label><label class="field"><span>Detraibilità %</span><input name="deductibility_percent" inputmode="decimal" value="100"></label><label class="field"><span>IVA detraibile</span><input name="deductible_vat" inputmode="decimal"><small>Può essere inferiore all’IVA in caso di indetraibilità.</small></label>
</div><div class="form-actions"><button class="button primary" type="submit"><?= View::icon('check') ?> Registra movimento</button></div></form></details>
