<?php
use Luna\Core\Csrf;
use Luna\Core\View;
$balance = (float) $settlement['balance'];
$resultClass = $balance > 0.005 ? 'debit' : ($balance < -0.005 ? 'credit' : 'neutral');
$registerLabels = ['SALES' => 'Registro vendite', 'PURCHASES' => 'Registro acquisti', 'CORRISPETTIVI' => 'Registro corrispettivi'];
$detailsByRegister = [];
foreach ($details as $detail) { $detailsByRegister[(string) $detail['register_type']][] = $detail; }
?>
<section class="page-intro compact"><div><a class="back-link" href="/accounting/vat-settlements?year=<?= (int) $settlement['period_year'] ?>">← Liquidazioni IVA</a><span class="eyebrow"><?= $settlement['period_type'] === 'MONTHLY' ? 'Liquidazione mensile' : 'Liquidazione trimestrale' ?></span><h1>Periodo <?= (int) $settlement['period_number'] ?> · <?= (int) $settlement['period_year'] ?></h1><p>Calcolata il <?= View::date($settlement['calculated_at'] ?: $settlement['updated_at']) ?></p></div><span class="badge status-<?= strtolower((string) $settlement['status']) ?> settlement-status"><?= View::e(View::label($settlement['status'])) ?></span></section>

<section class="vat-result-hero <?= $resultClass ?>">
  <div><span class="section-kicker">Esito della liquidazione</span><h2><?= $balance > 0.005 ? 'IVA DA VERSARE' : ($balance < -0.005 ? 'CREDITO IVA DA RIPORTARE' : 'LIQUIDAZIONE A ZERO') ?></h2><strong><?= View::money(abs($balance)) ?></strong></div>
  <div class="vat-equation" aria-label="Formula di calcolo"><span><b><?= View::money($settlement['vat_debit']) ?></b> IVA a debito</span><i>−</i><span><b><?= View::money($settlement['vat_credit']) ?></b> IVA detraibile</span><i>−</i><span><b><?= View::money($settlement['previous_credit']) ?></b> credito precedente</span><i>+</i><span><b><?= View::money($settlement['interest_amount']) ?></b> interessi</span></div>
</section>

<section class="accounting-kpis settlement-kpis vat-summary-kpis"><article><span>IVA a debito</span><strong><?= View::money($settlement['vat_debit']) ?></strong></article><article><span>IVA detraibile</span><strong><?= View::money($settlement['vat_credit']) ?></strong></article><article><span>Credito precedente</span><strong><?= View::money($settlement['previous_credit']) ?></strong></article><article><span>Interessi</span><strong><?= View::money($settlement['interest_amount']) ?></strong></article></section>

<section class="card data-card vat-detail-card"><div class="card-header"><div><span class="section-kicker">Prospetto di calcolo</span><h2>Dettaglio per registro, articolo e aliquota IVA</h2><p>Le note di credito sono esposte con imponibile e imposta negativi.</p></div><div class="export-actions"><a class="button ghost" href="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/export/pdf">PDF</a><a class="button ghost" href="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/export/xlsx">XLSX</a><a class="button ghost" href="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/export/csv">CSV</a></div></div>
<?php foreach ($detailsByRegister as $register => $registerDetails): ?>
<div class="vat-register-section"><h3><?= View::e($registerLabels[$register] ?? $register) ?></h3><div class="table-wrap"><table><thead><tr><th>Codice / articolo IVA</th><th>Aliquota</th><th>Natura / riferimento</th><th class="numeric">Imponibile</th><th class="numeric">IVA</th><th class="numeric">IVA detraibile</th></tr></thead><tbody><?php foreach ($registerDetails as $detail): ?><tr><td><span class="badge"><?= View::e($detail['vat_code']) ?></span><small class="cell-subtitle"><?= View::e($detail['vat_description']) ?></small></td><td class="numeric"><?= number_format((float) $detail['vat_rate'], 2, ',', '.') ?>%</td><td><?= View::e($detail['vat_nature'] ?: '—') ?><small class="cell-subtitle"><?= View::e($detail['vat_legal_reference'] ?: '') ?></small></td><td class="numeric <?= (float) $detail['taxable_amount'] < 0 ? 'danger-text' : '' ?>"><?= View::money($detail['taxable_amount']) ?></td><td class="numeric <?= (float) $detail['vat_amount'] < 0 ? 'danger-text' : '' ?>"><?= View::money($detail['vat_amount']) ?></td><td class="numeric"><?= View::money($detail['deductible_vat']) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr><th colspan="3">Totale <?= View::e(mb_strtolower($registerLabels[$register] ?? $register)) ?></th><th class="numeric"><?= View::money(array_sum(array_column($registerDetails, 'taxable_amount'))) ?></th><th class="numeric"><?= View::money(array_sum(array_column($registerDetails, 'vat_amount'))) ?></th><th class="numeric"><?= View::money(array_sum(array_column($registerDetails, 'deductible_vat'))) ?></th></tr></tfoot></table></div></div>
<?php endforeach; ?>
<?php if (!$details): ?><p class="empty-state">Nessun movimento IVA nel periodo.</p><?php endif; ?>
<div class="vat-detail-total"><span>Risultato liquidazione</span><strong><?= $balance >= 0 ? 'Da versare' : 'Credito' ?>: <?= View::money(abs($balance)) ?></strong></div></section>

<?php if ($settlement['notes']): ?><section class="card accounting-note"><span class="section-kicker">Note</span><p><?= nl2br(View::e($settlement['notes'])) ?></p></section><?php endif; ?>

<section class="card settlement-actions"><div><span class="section-kicker">Gestione</span><h2>Stato liquidazione</h2><p>Una liquidazione definitiva o pagata blocca le modifiche ai movimenti IVA del periodo.</p></div><div class="inline-actions">
<?php if ($settlement['status'] === 'CALCULATED'): ?><form method="post" action="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/status" data-confirm="Rendere definitiva la liquidazione e bloccare il periodo?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><input type="hidden" name="status" value="SUBMITTED"><button class="button primary" type="submit"><?= View::icon('check') ?> Rendi definitiva</button></form><?php endif; ?>
<?php if (in_array($settlement['status'], ['SUBMITTED', 'PAID'], true)): ?><form method="post" action="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/status" class="inline-form"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><input type="hidden" name="status" value="PAID"><label>Data pagamento <input type="date" name="payment_date" value="<?= View::e($settlement['payment_date'] ?: date('Y-m-d')) ?>" required></label><label>Riferimento versamento F24 <input name="payment_reference" maxlength="190" value="<?= View::e($settlement['payment_reference'] ?? '') ?>" required></label><button class="button primary" type="submit">Registra pagamento</button></form><?php endif; ?>
<?php if (in_array($settlement['status'], ['SUBMITTED','PAID'], true)): ?><form method="post" action="/accounting/vat-settlements/<?= (int) $settlement['id'] ?>/status" data-confirm="Riaprire il periodo IVA e consentire nuove modifiche?"><input type="hidden" name="_token" value="<?= View::e(Csrf::token()) ?>"><input type="hidden" name="status" value="CALCULATED"><button class="button ghost" type="submit">Riapri periodo</button></form><?php endif; ?>
</div></section>
