<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:types="http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types" targetNamespace="http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types" version="1.0">
  <xsd:element name="fileSdI" type="types:fileSdI_Type"/>
  <xsd:element name="fileSdIConMetadati" type="types:fileSdIConMetadati_Type"/>
  <xsd:element name="rispostaRiceviFatture" type="types:rispostaRiceviFatture_Type"/>
  <xsd:complexType name="fileSdI_Type"><xsd:sequence><xsd:element name="IdentificativoSdI" type="types:identificativoSdI_Type"/><xsd:element name="NomeFile" type="types:nomeFile_Type"/><xsd:element name="File" type="xsd:base64Binary"/></xsd:sequence></xsd:complexType>
  <xsd:complexType name="fileSdIConMetadati_Type"><xsd:sequence><xsd:element name="IdentificativoSdI" type="types:identificativoSdI_Type"/><xsd:element name="NomeFile" type="types:nomeFile_Type"/><xsd:element name="File" type="xsd:base64Binary"/><xsd:element name="NomeFileMetadati" type="types:nomeFile_Type"/><xsd:element name="Metadati" type="xsd:base64Binary"/></xsd:sequence></xsd:complexType>
  <xsd:complexType name="rispostaRiceviFatture_Type"><xsd:sequence><xsd:element name="Esito"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:enumeration value="ER01"/></xsd:restriction></xsd:simpleType></xsd:element></xsd:sequence></xsd:complexType>
  <xsd:simpleType name="identificativoSdI_Type"><xsd:restriction base="xsd:integer"><xsd:totalDigits value="12"/></xsd:restriction></xsd:simpleType>
  <xsd:simpleType name="nomeFile_Type"><xsd:restriction base="xsd:string"><xsd:pattern value="[a-zA-Z0-9_\.]{9,50}"/></xsd:restriction></xsd:simpleType>
</xsd:schema>
